DELETE http://localhost:3003/api/blogs/6681817a24fb3b989c1f175e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2NjgwODk5NzhjMTAwNGE5ODNhZjE4MmQiLCJpYXQiOjE3MTk2OTk4OTZ9.C0_nsYbod_M_CuYyeiIrcvUMLpMiJtJpyExrNkQNFmA

###
DELETE http://localhost:3003/api/blogs/668181a75e521e7b749ed7a7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2NjgwODk5NzhjMTAwNGE5ODNhZjE4MmQiLCJpYXQiOjE3MTk2OTk4OTZ9.C0_nsYbod_M_CuYyeiIrcvUMLpMiJtJpyExrNkQNFmA

###
DELETE http://localhost:3003/api/blogs/668181bd82b340e1323ff74b
Content-Type: application/json
Authorization: Bearer invalidtoken

###
DELETE http://localhost:3003/api/blogs/668181bd82b340e1323ff74b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2Njc5YmRhNjk3MTg3YzllZjU3MDhjMmIiLCJpYXQiOjE3MTk3NjM3NTF9.kifgasNZuuC01P0lkXcFlZbTuIvQOsUlGK76FMXuJXo